"""
Biblioteca de temas pré-definidos para certificados

Este módulo define os temas disponíveis para uso no sistema NEPEMCERT.
Cada tema contém configurações específicas para personalizar a aparência dos certificados.
"""

# Temas pré-definidos para o sistema NEPEMCERT
PREDEFINED_THEMES = {
    "Acadêmico Clássico": {
        "font_family": "Times, 'Times New Roman', serif",
        "heading_color": "#003366",
        "text_color": "#333333",
        "background_color": "#fffff8",
        "border_color": "#8c7853",
        "border_width": "3px",
        "border_style": "double",
        "margin": "40px",
        "heading_size": "42px",
        "title_font_size": "48px",
        "text_size": "20px",
        "content_font_size": "24px",
        "name_font_size": "38px",
        "name_color": "#003366",
        "title_color": "#003366",
        "title_text": "Certificado de Excelência",
        "intro_text": "Certifica-se que",
        "participation_text": "participou com distinção do evento",
        "footer_style": "classic",
        "signature_color": "#000033",
        "signature_text_size": "14px",
        "background_image": None
    },
    "Executivo Premium": {
        "font_family": "Helvetica, Arial, sans-serif",
        "heading_color": "#1c2a48",
        "text_color": "#2c3e50",
        "background_color": "#ffffff",
        "border_color": "#c9a84b",
        "border_width": "2px",
        "border_style": "solid",
        "margin": "35px",
        "heading_size": "38px",
        "title_font_size": "44px",
        "text_size": "18px",
        "content_font_size": "22px",
        "name_font_size": "36px",
        "name_color": "#1c2a48",
        "title_color": "#1c2a48",
        "title_text": "Certificado Profissional",
        "intro_text": "Este documento certifica que",
        "participation_text": "participou e concluiu com sucesso",
        "footer_style": "modern",
        "signature_color": "#333333",
        "signature_text_size": "14px",
        "background_image": None
    },
    "Contemporâneo Elegante": {
        "font_family": "Helvetica, Arial, sans-serif",
        "heading_color": "#2e3c50",
        "text_color": "#34495e",
        "background_color": "#f9f9f9",
        "border_color": "#cbd5e0",
        "border_width": "1px",
        "border_style": "solid",
        "margin": "30px",
        "heading_size": "36px",
        "title_font_size": "42px",
        "text_size": "18px",
        "content_font_size": "22px",
        "name_font_size": "34px",
        "name_color": "#5260c9",
        "title_color": "#2e3c50",
        "title_text": "Certificado",
        "intro_text": "Conferimos este certificado a",
        "participation_text": "pela participação no evento",
        "footer_style": "minimalist",
        "signature_color": "#2e3c50",
        "signature_text_size": "14px",
        "background_image": None
    },
    "Diplomático Oficial": {
        "font_family": "Palatino, 'Times New Roman', serif",
        "heading_color": "#1a3a5f",
        "text_color": "#333333",
        "background_color": "#f8f8f0",
        "border_color": "#8d734a",
        "border_width": "4px",
        "border_style": "double",
        "margin": "45px",
        "heading_size": "44px",
        "title_font_size": "52px",
        "text_size": "20px",
        "content_font_size": "26px",
        "name_font_size": "40px",
        "name_color": "#1a3a5f",
        "title_color": "#1a3a5f",
        "title_text": "Certificado Oficial",
        "intro_text": "A instituição certifica que",
        "participation_text": "participou oficialmente do evento",
        "footer_style": "formal",
        "signature_color": "#333333",
        "signature_text_size": "16px",
        "background_image": None
    },
    "Minimalista Moderno": {
        "font_family": "Helvetica, Arial, sans-serif",
        "heading_color": "#202020",
        "text_color": "#404040",
        "background_color": "#ffffff",
        "border_color": "#e0e0e0",
        "border_width": "1px",
        "border_style": "solid",
        "margin": "35px",
        "heading_size": "34px",
        "title_font_size": "40px", 
        "text_size": "18px",
        "content_font_size": "22px",
        "name_font_size": "32px",
        "name_color": "#202020",
        "title_color": "#202020",
        "title_text": "Certificado de Conclusão",
        "intro_text": "Este documento certifica que",
        "participation_text": "participou e concluiu",
        "footer_style": "clean",
        "signature_color": "#404040",
        "signature_text_size": "14px",
        "background_image": None
    }
}
